#! /bin/bash

declare -A ECL_nav

ECL_editor_cmd="vim -c \"syntax spell toplevel\""

ECL_nav[pdf]="zathura"
ECL_nav[djvu]="zathura"
ECL_nav[epub]="zathura"
ECL_nav[jpg]="display"
ECL_nav[jpeg]="display"
ECL_nav[gif]="display"
ECL_nav[png]="display"
ECL_nav[mp4]="ffplay"
ECL_nav[avi]="ffplay"
ECL_nav[webm]="ffplay"
ECL_nav[mpeg]="ffplay"

