#! /bin/bash

function bkl(){
    x=/sys/class/backlight/intel_backlight/brightness
    if [[ "$1" = "-inc" ]] || [[ "$1" = "--increase" ]]; then
        y=$(<$x)
        bkl=$(bc <<< "$y+600")
        echo $bkl | tee $x
    elif [[ "$1" = "-dec" ]] || [[ "$1" = "--decrease" ]]; then
        y=$(<$x)
        bkl=$(bc <<< "$y-600")
        echo $bkl | tee $x
    else
        echo "Option not defined."
    fi
}
