#! /bin/bash

source $ECL_install_dir/config/eclrc

# fast navigation with .
    function .() {
        ext=${1##*.}
        for i in ${!ECL_nav[@]}; do
            if  [[ "$i" == "$ext" ]]; then 
                    eval "${ECL_nav[$i]} $1"
                    break
            else
                continue
            fi
        done
        if [[ -z $1 ]]; then
            ls --color=auto --group-directories-first
        elif [[ -d "$1" ]]; then 
            cd $1 && ls --color=auto --group-directories-first
        elif [[ -z $ext ]]; then
            eval "$ECL_editor_cmd" $1
        elif [[ ! ${!ECL_nav[@]} =~ "$ext" ]]; then
            eval "$ECL_editor_cmd" $1
        fi 
    }
# .i to navigate to the ith-1 file
    for i in {1..100}; do
        eval "function .$i(){
            files=(\$(ls))
            x=$(($i-1))
            . \${files[\$x]}
        }
        "
    done

## list hidden files with ".," or ",."
    alias ,.="ls -a --color=auto --group-directories-first"
    alias .,="ls -a --color=auto --group-directories-first"
## use "~" to move to $HOME and list files
    alias ~="cd $HOME && ls --color=auto --group-directories-first"
## move to parent dirs with multiple dots
    alias ..=" cd .. && ls --color=auto --group-directories-first"
    alias ...=" cd - > /dev/null"

