#! /bin/bash

# "mk" function.
## "mk -d" to make a dir. "mk -f" to make a file.
    function mk(){
        if [[ "$1" == "-f" || "$1" == "--file" ]]; then
            if [ -n $2 ]; then
                touch $2
            fi
        elif [[ "$1" = "-d" || "$1" = "--dir" ]]; then
            if [ -n $2 ]; then
                mkdir -p $2
            fi
        elif [[ "$1" = "-l" || "$1" = "--link" ]]; then
            if [ -n $2 ] || [ -n $3 ]; then
                ln -s $2 $3
            fi
        else
            echo "Option not defined for the \"mk\" function. Try:  
    * \"mk -f\" for files;  
    * \"mk -d\" for directories;
    * \"mk -l\" for symbolic links."

        fi
    }

## aliases
    alias mkf="mk -f"
    alias mkd="mk -d"
    alias mkl="mk -l"


