#! /bin/bash

source $ECL_install_dir/config/eclrc

# Fast navigation with "."
## use ". file" or ". $i"  to open the ith file 
    function .() {
        for i in ${!ECL_nav[@]}; do
            ext=${1##*.}
            if  [[ "$i" == "$ext" ]]; then
                if [[ -n "${ECL_nav[$i]}" ]]; then
                    eval "${ECL_nav[$i]} $1 & disown" 
                    break
                else
                    eval "xdg-open $1"
                    break
                fi
            elif [[ -z $1 ]]; then
                ls --color=auto --group-directories-first
                break
            elif [[ -d "$1" ]]; then 
                cd $1 && ls --color=auto --group-directories-first
                break
            elif [[ "$1" =~ ^[0-9]+$ ]]; then
                arr=($PWD/*)
                x=$(($1-1))
                . ${arr[$x]}
                break
            else
                command xdg-open $1
                break
            fi
        done
    }
## list hidden files with ".," or ",."
    alias ,.="ls --color=auto --group-directories-first"
    alias .,="ls --color=auto --group-directories-first"
## use "~" to move to $HOME and list files
    alias ~="cd ~/ && ls --color=auto --group-directories-first"
## move to parent dirs with multiple dots
    alias ..=" cd .. && ls --color=auto --group-directories-first"
    alias ...=" cd - > /dev/null"

