#! /bin/bash    

# VL FUNCTIOn

    function vl(){
        if [[ "$1" == "-s" ]] || [[ "$1" == "-st" ]] || [[ "$1" == "--start" ]]; then
            pulseaudio --start
        elif [[ "$1" == "-k" ]] || [[ "$1" == "--kill" ]]; then 
            pulseaudio --kill
        elif   [[ "$1" == "-h" ]] || [[ "$1" == "-hd" ]] || [[ "$1" == "--hdmi" ]]; then
            pacmd set-card-profile 0 output:hdmi-stereo
        elif  [[ "$1" == "-a" ]] || [[ "$1" == "-an" ]] || [[ "$1" == "--analog" ]]; then
            pacmd set-card-profile 0 output:analog-stereo
        elif [[ "$1" == "-i" ]] || [[ "$1" == "--inc" ]] || [[ "$1" == "--increase" ]]; then
            amixer set Master 5%+
        elif [[ "$1" == "-d" ]] || [[ "$1" == "--dec" ]] || [[ "$1" == "--decrease" ]]; then
            amixer set Master 5%-
        elif [[ "$1" == "-m" ]] || [[ "$1" == "--mute" ]]; then
            amixer set Master toggle
        elif [[ "$1" == "--help" ]]; then
            echo "help..."
        elif [[ -z "$1" ]]; then
            alsamixer -g
        else
            echo "Option not defined for the function \"vl\"."
        fi
    }

# ALIASES

alias vls="vl -s"
alias vlk="vl -k"
alias vlh="vl -h"
alias vla="vl -a"
alias vli="vl -i"
alias vld="vl -d"
alias vlm="vl -m"






